fromState = {
  "alabama": "green-party-of-alabama",
  "alaska": "green-party-of-alaska",
  "arizona": "arizona-green-party",
  "arkansas": "green-party-of-arkansas",
  "california": "green-party-of-california",
  "colorado": "green-party-of-colorado",
  "connecticut": "green-party-of-connecticut",
  "createDict": "creat-a-dict-for-this-page",
  "delaware": "green-party-of-delaware",
  "district-of-columbia": "dc-statehood-green-party",
  "florida": "green-party-of-florida",
  "georgia": "georgia-green-party",
  "hawaii": "the-green-party-of-hawaii",
  "idaho": "green-party-of-idaho",
  "illinois": "illinois-green-party",
  "indiana": "indiana-green-party",
  "iowa": "iowa-green-party",
  "kansas": "kansas",
  "kentucky": "the-kentucky-green-party",
  "louisiana": "green-party-of-louisiana",
  "maine": "maine-green-independent-party",
  "maryland": "maryland-green-party",
  "massachusetts": "green-rainbow-party-of-massachusetts",
  "michigan": "green-party-of-michigan",
  "minnesota": "green-party-of-minnesota",
  "mississippi": "green-party-of-mississippi",
  "missouri": "missouri-green-party",
  "montana": "montana-green-party",
  "nebraska": "nebraska-green-party",
  "nevada": "green-party-of-nevada",
  "new-hampshire": "green-party-of-new-hampshire",
  "new-jersey": "green-party-of-new-jersey",
  "new-mexico": "green-party-of-new-mexico",
  "new-york": "green-party-of-new-york",
  "north-carolina": "north-carolina-green-party",
  "north-dakota": "north-dakota-green-party",
  "ohio": "ohio-green-party",
  "oklahoma": "oklahoma",
  "oregon": "pacific-green-party-of-oregon",
  "pennsylvania": "green-party-of-pennsylvania",
  "rhode-island": "green-party-of-rhode-island",
  "south-carolina": "south-carolina-green-party",
  "south-dakota": "south-dakota",
  "tennessee": "green-party-of-tennessee",
  "texas": "green-party-of-texas",
  "utah": "green-party-of-utah",
  "virgin-islands": "green-party-of-the-virgin-islands",
  "virginia": "green-party-of-virginia",
  "washington": "green-party-of-washington-state",
  "west-virginia": "west-virginia-mountain-party",
  "wisconsin": "wisconsin-green-party",
  "wyoming": "wyoming-green-party"
}
toState = {}
for key,value in fromState.items():
    toState [value] = key

